In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, -1], float) # the array type can also be specified at creation time
print(type(a))
print(a.dtype) # this shows the type of the array either integer or float number
print(sorted(a)) # this sort the array

<class 'numpy.ndarray'>
float64
[-1.0, 0.0, 1.0, 2.0, 3.0]


In [22]:
create_array = np.arange(10) # this helps create standard arrays filled to the given range
print(create_array)
customize_array = np.arange(1, 9, 2) # start, end, step
print(customize_array)
print(create_array[::-1]) # this reverse the array order

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [21]:
np.random.rand(5) # generate random number per the given step

array([0.09798262, 0.64805563, 0.96975119, 0.84603519, 0.87736874])

In [18]:
# ccreate an array of zeros (initial-row, lenght to be in a row, overall lenght)
np.zeros((5,2,5)) 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.ones((5,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [20]:
np.arange(10, 25, 5)

array([10, 15, 20])