In [4]:
import numpy as np
np.array(['1','2','3'])

array(['1', '2', '3'], dtype='<U1')

In [6]:
height = [1.2, 2.4, 3.4, 2.9, 4.7]
weight = [2.3, 5.8, 8.2, 2.8, 6.4]

np_height = np.array(height)
np_height

array([1.23, 2.45, 3.45, 2.98, 4.78])

In [7]:
np_weight = np.array(weigth)
np_weight

array([2.34, 5.89, 8.23, 2.87, 6.43])

In [9]:
bmi = np_weight / np_height ** 2
bmi

array([1.54669839, 0.98125781, 0.69145138, 0.32318364, 0.28142014])

In [10]:
type(bmi)

numpy.ndarray

In [11]:
type(np_weight)

numpy.ndarray

In [12]:
type(np_height)

numpy.ndarray

In [13]:
np_2d = np.array([
    [2.3, 5.8, 8.2, 2.8, 6.4],
    [1.2, 2.4, 3.4, 2.9, 4.7]
])
np_2d

array([[2.3, 5.8, 8.2, 2.8, 6.4],
       [1.2, 2.4, 3.4, 2.9, 4.7]])

In [15]:
np_2d.shape

(2, 5)

Generating raw data with numpy simulating functions. Sampled 2random distributions 5000 times to create an height and weight range and used a column stack to pace them into 2 columns

In [20]:
simulated_height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
simulated_weight = np.round(np.random.normal(60.32, 15, 5000), 2)
simulated_data_result = np.column_stack((simulated_height, simulated_weight))
simulated_data_result

array([[ 1.56, 43.66],
       [ 1.67, 87.62],
       [ 1.52, 73.91],
       ...,
       [ 1.79, 58.93],
       [ 1.74, 65.1 ],
       [ 2.02, 48.96]])

In [21]:
np.mean(simulated_data_result[:,0])

1.7513920000000003

In [22]:
np.median(simulated_data_result[:,0])

1.75

In [27]:
np.corrcoef(simulated_data_result[:,0], simulated_data_result[:,1])
# This help check if the height and weight in the data are correlated

array([[1.        , 0.00958019],
       [0.00958019, 1.        ]])

In [29]:
np.std(simulated_data_result[:,0])
# this help look for the standard deviation

0.2009714963272155

In [30]:
np.sum(simulated_data_result[:,0])

8756.960000000001

In [31]:
np.sort(simulated_data_result[:,0])

array([1.02, 1.04, 1.08, ..., 2.35, 2.39, 2.49])

In [33]:
bmi > 1

array([ True, False, False, False, False])

In [37]:
bmi[bmi > 1]

array([1.54669839])